package domain

// GeneratePersonaRequest represents the user traits requested to generate a persona.
type GeneratePersonaRequest struct {
	Traits []string `json:"traits"`
}

// PersonaStats represents the numeric stats for the generated drag queen.
type PersonaStats struct {
	Glamour int `json:"glamour"`
	Comedy  int `json:"comedy"`
	Dance   int `json:"dance"`
	Camp    int `json:"camp"`
}

// PersonaResult represents the structured output generated by Gemini.
type PersonaResult struct {
	DragName              string       `json:"dragName"`
	Bio                   string       `json:"bio"`
	Stats                 PersonaStats `json:"stats"`
	ImageGenerationPrompt string       `json:"imageGenerationPrompt"`
}
